name: Suite de Tests Automáticos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testear:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4
    
    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install pytest tabulate
        
    - name: Correr tests Ejercicio 02
      working-directory: ./ejercicio_02_validador
      run: python -m pytest --ignore=tests/test_db_unittest_bis.py
      #run: python -m pytest
      
    - name: Correr tests Ejercicio 07
      working-directory: ./ejercicio_07_stock
      run: python -m pytest